repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
            -   id: check-yaml
    -   repo: local
        hooks:
            -   id: formatter
                name: formatter
                entry: bash -c "black customercounter/"
                language: system
                fail_fast: True
    -   repo: local
        hooks:
            -   id: reorder-python-imports
                name: reorder-python-imports
                entry: bash -c 'isort customercounter/'
                language: system
                fail_fast: True
    
    -   repo: local
        hooks:
            -   id: mypy-checker
                name: mypy-checker
                entry: bash -c "mypy customercounter/"
                language: system
                fail_fast: True
    -   repo: local
        hooks:
            - id: pytest-check
              name: pytest-check
              entry: bash -c 'pytest'
              language: system
